# Generated by Django 4.2.7 on 2023-11-19 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.TextField(max_length=200)),
                ('offer_name', models.TextField(max_length=200)),
                ('interest', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('offer_type', models.CharField(choices=[('Lokata', 'Lokata'), ('Konto oszczędnościowe', 'Konto oszczędnościowe')])),
                ('offer_length_months', models.PositiveIntegerField(null=True)),
                ('client_type', models.CharField(choices=[('Indywidualny', 'Indywidualny'), ('Biznesowy', 'Biznesowy')])),
                ('offer_kind', models.CharField(choices=[('Nowi klienci', 'Nowi klienci'), ('Starzy klienci', 'Starzy klienci'), ('Nowe środki', 'Nowe środki')], null=True)),
                ('min_resources', models.IntegerField(null=True)),
                ('max_resources', models.IntegerField(null=True)),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('USD', 'USD')])),
                ('additional_info', models.TextField(null=True)),
                ('valid_from_date', models.DateField(null=True)),
            ],
        ),
    ]
